9 - Update to Polymer 2.x - part 3
Neovici/cosmoz-i18next pull request #14
Opened 2019-05-08 09:27 UTC by dotpointer

Update to Polymer 2.x - part 3.

Need some help on this one. The demo warns that getTranslations is not declared, but the demo works and the function runs. This error was there before this pull request. `yarn lint` also warns that `t` and `_` are not declared in `cosmoz-t.html`,  but the file both imports the behavior and mentions it in `mixinBehaviors`.

Issue is #9.

2019-05-08 09:30 UTC, nomego requested changes

2019-05-08 09:30 UTC, nomego commented on cosmoz-t.html
> +			Cosmoz.TranslatableBehavior
Use `Cosmoz.Mixins.translatable(Polymer.Element)` rather

2019-05-08 09:30 UTC, nomego commented on demo/index.html
> +				Cosmoz.TranslatableBehavior
Cosmoz.Mixins.translatable

2019-05-08 09:34 UTC, dotpointer commented on cosmoz-t.html
> +			Cosmoz.TranslatableBehavior
Changed.

2019-05-08 09:34 UTC, dotpointer commented on demo/index.html
> +				Cosmoz.TranslatableBehavior
Changed.

2019-05-08 09:38 UTC, dotpointer commented
@megheaiulian Do you have any idea why `yarn lint` fails?

2019-05-08 15:41 UTC, nomego approved these changes
One code climate / eslint issue can be fixed.

2019-05-15 08:45 UTC, merged

2019-05-15 08:49 UTC, dotpointer commented
> One code climate / eslint issue can be fixed.

I figure the problem is that `properties()` in cosmoz-i18next/cosmoz-i18next.js:221-222 has 38 lines which exceeds the allowed 30.

I tried fixing this twice, first by adding `// eslint-disable-next-line max-lines-per-function` above the function, and then by replacing that with `// eslint-disable-line max-lines-per-function` after the function. `yarn lint` did not complain, Code Climate however continues to do so.

Since you approved I took the opportunity to merge it anyways so we go forward with the progress in #815.

@nomego Please advice how to fix this for Code Climate if you know how to do it, then I can try to fix it.